apiVersion: apps/v1
kind: Deployment
metadata:
  name: joanna-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joanna-web
  template:
    metadata:
      labels:
        app: joanna-web
    spec:
      containers:
        - name: joanna-web
          image: kurkapsiurka/hello-joanna:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: joanna-web
  namespace: default
spec:
  type: NodePort
  selector:
    app: joanna-web
  ports:
    - port: 8080
      targetPort: 80
