apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: joanna-web
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image:
      repository: kurkapsiurka/hello-joanna
      tag: v2
    service:
      type: NodePort
      port: 8080
      targetPort: 80
