apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: joanna-web
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image:
      repository: joannalogin/hello-joanna
      tag: v1
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 8080
      targetPort: 80
