apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: joanna-web
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/my-cluster/joanna-web
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
